[package]
name = "rhodos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "librhodos"
path = "src/lib.rs"

[[bin]]
name = "rhodos"
path = "src/bin/bin.rs"

[dependencies]
chrono = "~0.4"
diesel = { version = "2.0.0", features = ["chrono", "postgres"] }
docopt = "1"
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }
slog = "2.7.0"
slog-async = "2.7.0"
slog-term = "2.7.0"
