[package]
name = "rhodus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "librhodus"
path = "src/lib.rs"

[[bin]]
name = "rhodus"
path = "src/bin/bin.rs"

[dependencies]
docopt = "1"
serde = { version = "1", features = ["derive"] }
slog = "2.7.0"
slog-async = "2.7.0"
slog-term = "2.7.0"
