//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub use super::account::Entity as Account;
pub use super::content::Entity as Content;
pub use super::instance::Entity as Instance;
pub use super::microblog::Entity as Microblog;
