//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub use super::account::Entity as Account;
pub use super::client_app::Entity as ClientApp;
pub use super::content::Entity as Content;
pub use super::instance::Entity as Instance;
pub use super::microblog::Entity as Microblog;
pub use super::user::Entity as User;
pub use super::user_token::Entity as UserToken;
